### ISSUE TITLE
Remove `validation-runtime` module

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/validation#32]
Once #31 is merged, the code of `validation-runtime` module will no longer be used.

Therefore, it will have to be removed from the VCS.

**Comment by alexander-yevsyukov** [comment]
BTW, the types `ListOfAnys` and `MapOfAnys` from this module are already available from `base`, if needed.

**Comment by alexander-yevsyukov** [comment]
Addressed by #31.
